### ISSUE TITLE
This idea of using react-app as upstream is failing.

### ISSUE THREAD

**Issue by AubreyHewes** [kingsquare/eslint-config-kingsquare#6]
Due to the react-app upstream requirement; it is required to update the react-app to a usable version..

This leaves no leeway for own eslint... so introduces problems in eslint configuration within IDE, for projects that want latest TS and linting.. but do not want to update "the complete project".

Though possibly the point is moot as we may be moving back to airbnb due to the organisational changes.

**Comment by Reggino** [comment]
True, true. Suggestions welcome :-)

**Comment by AubreyHewes** [comment]
@Reggino There are no suggestions...

I am currently removing eslint-ks from projects mainly due to the incompatibility... (not being able to update react-scripts/eslint/prettier/etc.. the combinations)... 
removing and using an own with react scripts ^4 and react ^17... was a node_modules from 4gb to 1gb (mostly babel stuff) (not that 1gb is good... but better x )

**Comment by AubreyHewes** [comment]
Though where we are going (no names)... it is just airbnb.. which has no react or TS checks.. also their own code has no explicit requirement

**Comment by AubreyHewes** [comment]
the react-app style limits us as we want a specific style...
we can not decide on a style.. so we want the react-app style...
The react-app style enforces versions of other libs

**Comment by AubreyHewes** [comment]
This is not really an issue as [everyone knows](https://www.youtube.com/watch?v=Lin-a2lTelg)

so will close it :-D
